name: Tunein
description: music player app.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayer:
    git:
      url: https://github.com/moda20/audioplayer
  path_provider: ^0.4.1
  rxdart: ^0.23.1
  sliding_up_panel: ^0.3.4
  shared_preferences: ^0.5.3+1
  media_notification:
    git:
      url: https://github.com/moda20/flutter_media_notification
  simple_permissions:
    git:
      url: https://github.com/tq-systems/simple_permissions.git
  get_it: ^1.0.3+1
  crypto: ^2.0.6
  uuid: ^2.0.2
  page_transition: "^1.1.5"
  flutter_custom_dialog: ^1.0.14
  fading_edge_scrollview: ^1.1.0
  audio_service: ^0.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
 

flutter:
  assets:
    - images/
  fonts:
    - family: Boxicons
      fonts:
        - asset: fonts/boxicons.ttf
          weight: 400

  
  uses-material-design: true
