name: Tunein
description: music player app.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayer:
    git:
      ref: master
      url: https://github.com/moda20/audioplayer
  path_provider: ^1.1.0
  flutter_reorderable_list:
    git:
      url: https://github.com/martinory/flutter_reorderable_list.git
  rxdart: ^0.23.1
  sliding_up_panel: ^0.3.4
  shared_preferences: ^0.5.3+1
  media_notification:
    git:
      url: https://github.com/moda20/flutter_media_notification
  simple_permissions:
    git:
      url: https://github.com/tq-systems/simple_permissions.git
  get_it: ^1.0.3+1
  crypto: ^2.0.6
  uuid: ^2.0.2
  page_transition: "^1.1.5"
  flutter_custom_dialog: ^1.0.14
  fading_edge_scrollview: ^1.1.0
  string_similarity: ^1.0.1
  flushbar: 1.9.1
  settings_ui:
    git:
      url: https://github.com/moda20/flutter-settings-ui.git
  flutter_i18n: ^0.13.0
  marquee: ^1.3.1
  flutter_isolate:
    git:
      url: https://github.com/rmawatson/flutter_isolate.git
  dio: ^3.0.9
  dio_flutter_transformer: ^3.0.2
  morpheus: ^1.2.2+1
  animations: ^1.0.0+5
  connectivity: ^0.4.8+2
  badges: ^1.1.1
  popup_menu: ^1.0.5
  upnp:
    git:
      url: https://github.com/SpinlockLabs/upnp.dart
dev_dependencies:
  flutter_test:
    sdk: flutter
 

flutter:
  assets:
    - images/
    - locale/
  fonts:
    - family: Boxicons
      fonts:
        - asset: fonts/boxicons.ttf
          weight: 400
    - family: Fontawesome
      fonts:
        - asset: fonts/fa.ttf
          weight: 400



  
  uses-material-design: true
